### ISSUE TITLE
Hashtag

### ISSUE THREAD

**Issue by AltCoinBuilders** [AdSoNaTuRaL/adsonatural-bot#1]
Instead of using a hashtag isit possible to use a URL to a certain tweet from a user? so i can put that URL in the config then it only likes, retweets and follows that user?

**Comment by AdSoNaTuRaL** [comment]
I don't know if I understood correctly, but you can check https://publish.twitter.com/# and https://developer.twitter.com/en/docs/twitter-for-websites what seems to do what you want, according to my understanding.

If not, let me know.
Regards!

**Comment by AltCoinBuilders** [comment]
So instead of us typing in a hashtag for the bot to retweet. 

would it be possible if we can put a URL/Link there direct to a specific tweet of our choice which then it will retweet, like that tweet then also follow the user? 

so instead of it querying #bot and retweeting every tweet with #bot it will only retweet the one of our choice with the URL we put in

**Comment by AdSoNaTuRaL** [comment]
> would it be possible if we can put a URL/Link there direct to a specific tweet of our choice which then it will retweet, like that tweet then also follow the user?

Yes, with one of the methods I mentioned above, this is possible. (Embedded Tweets)

> so instead of it querying #bot and retweeting every tweet with #bot it will only retweet the one of our choice with the URL we put in

Yes. But if you want to do that through a bot, you should check https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/overview

**Comment by AltCoinBuilders** [comment]
Would you be able to help change it to URL instead o Query = #hashtag?   id be happy to pay for this

**Comment by AdSoNaTuRaL** [comment]
Right! But let me understand what you really want. Do you want to retrieve a tweet by passing a URL and then being able to like, retweet, comment (maybe), is that it?

**Comment by AltCoinBuilders** [comment]
Thats correct, instead of enterting a hashtag in the config enter a url instead to that specific tweet

**Comment by AdSoNaTuRaL** [comment]
@AltCoinBuilders I'll let you know when it's ready, through this issue.

**Comment by AltCoinBuilders** [comment]
Perfect, Much Appreciated. What would the time scale on this be? ive been trying to do this for 2 days but my knowledge about twitter bots is very limited

**Comment by AdSoNaTuRaL** [comment]
About time, it’s hard to say because I’ve been working on other things this week, but I’ll try to fit that in.

**Comment by AltCoinBuilders** [comment]
Thanks,  Appreciate it

**Comment by AltCoinBuilders** [comment]
also if it could like and follow the user that would be great. Payment waiting once done :)

**Comment by AltCoinBuilders** [comment]
What would you want paying for this?

just to clarify it needs to be able to use a link instead of hashtag, follow, retweet, like and comment 

just getting the payment sorted :)

**Comment by AdSoNaTuRaL** [comment]
What purpose do you want to retweet a tweet through the url? Because if you have the url is it not easier to do this by the application itself? I think your best case would be exactly that: https://publish.twitter.com/#.


Try to explain to me, ty!
